### ISSUE TITLE
SUpport of Data Channels ?

### ISSUE THREAD

**Issue by elkekou** [NethServer/janus-gateway#31]
Hi,

thank you for your work building this RPM you save me time :).
I've one question i'm trying to setup "Nextcloud spreed signaling" which need "janus-gateway" so i found your rpm and install it.
I'm facing a problem with my signaling service which tell me "Could not initialize janus MCU (Data channels are not supported) ".
After some research it seems janus need to be compilde with "Data Channels support".
So before trying to compile myself... i've just one question is your rpm include version compiled with this directive?

Regards

**Comment by gsanchietti** [comment]
Hi,
looking at the spec, support for data channels is not supported in current build.
As far as I know, there is no official build for libusrsctp which is a dependency for data channels.

I did a couple of experiments, and it seems we can rebuild libusrsctp from here: https://packages.nntb.no/nornet-applications/fedora/25/i386/SRPMS/
Then, it's possible to compile janus with `--enable-data-channels`.

I do not know if this build can fit our scenario, let's ask @alepolidori and @Stell0.

Finally, you can find a test build as attachments of this comment. Just test them and let us know! ;)

(Files are gzipped because Github doesn't support attaching directly RPMs).

[janus-gateway-debuginfo-0.10.6-1.2.g3e3fb8b.ns7.x86_64.rpm.gz](https://github.com/NethServer/janus-gateway/files/5479920/janus-gateway-debuginfo-0.10.6-1.2.g3e3fb8b.ns7.x86_64.rpm.gz)
[libusrsctp-1.0.0~td117-1.x86_64.rpm.gz](https://github.com/NethServer/janus-gateway/files/5479923/libusrsctp-1.0.0.td117-1.x86_64.rpm.gz)

**Comment by elkekou** [comment]
Hi,
thanks for your answer and your help, i'll try this weekend ant let you know if it work.
Finally i've made a quick test, and it seems to does not work :( Still the same error...
Could not create janus MCU: Data channels are not supported

I will try to compile myself all the stuff, and give you more information if i get it to work. 
May be it's my janus config file which is not good.

Also does not understand the role of this package janus-gateway-debuginfo-0.10.6-1.2.g3e3fb8b.ns7.x86_64.rpm.gz
 sorry for my "noob" question but i'm not really good at compiling :).

**Comment by elkekou** [comment]
So finally i try myself to compile all the stuff following instructions on https://github.com/meetecho/janus-gateway
And it work only if i recompile libusrstp and janus.

So if i can help to make rpm with data channel.

Thanks
